name=MAX77972
version=1.0.0
author=Rubble Systems
maintainer=Rubble Systems
sentence=A C library for interfacing with the MAX77972 Battery Charger & Fuel Gauge
paragraph=A C library for interfacing with the MAX77972 Battery Charger & Fuel Gauge
category=Sensors
url=https://github.com/Rubble-Systems/MAX77972
architectures=*
